create table if not exists public.portfolio_projects (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    name_fr text not null,
    name_en text,
    short_summary_fr text not null,
    short_summary_en text,
    detailed_summary_fr text,
    detailed_summary_en text,
    my_role_fr text,
    my_role_en text,
    project_type text,
    organization text,
    location text,
    start_date date,
    end_date date,
    tools text[] not null default '{}',
    skills text[] not null default '{}',
    key_results jsonb not null default '[]'::jsonb,
    page_url text not null,
    github_url text,
    featured boolean not null default false,
    display_order integer not null default 0,
    verified boolean not null default false,
    source_file text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.portfolio_knowledge_items (
    id bigint generated by default as identity primary key,
    stable_key text not null unique,
    project_id bigint references public.portfolio_projects(id)
        on update cascade
        on delete set null,

    language text not null default 'fr',
    content_type text not null,
    category text not null,
    title text not null,
    content text not null,

    keywords text[] not null default '{}',
    skills text[] not null default '{}',
    tools text[] not null default '{}',
    question_variants text[] not null default '{}',

    source_url text,
    source_label text,
    source_file text,
    source_section text,

    priority integer not null default 50,
    verified boolean not null default false,
    approved_for_ai boolean not null default false,
    is_public boolean not null default true,

    embedding extensions.vector(384),

    metadata jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint portfolio_knowledge_language_check
        check (language in ('fr', 'en')),

    constraint portfolio_knowledge_priority_check
        check (priority between 0 and 100),

    constraint portfolio_knowledge_content_not_empty
        check (length(trim(content)) > 0)
);

create table if not exists public.portfolio_suggested_questions (
    id bigint generated by default as identity primary key,
    stable_key text not null unique,
    language text not null,
    label text not null,
    question text not null,
    category text,
    icon text,
    display_order integer not null default 0,
    active boolean not null default true,
    created_at timestamptz not null default now(),

    constraint portfolio_suggested_language_check
        check (language in ('fr', 'en'))
);

create table if not exists public.portfolio_sources (
    id bigint generated by default as identity primary key,
    stable_key text not null unique,
    source_type text not null,
    file_name text,
    page_url text,
    title text not null,
    description text,
    public_source boolean not null default true,
    last_reviewed_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.portfolio_chat_events (
    id bigint generated by default as identity primary key,
    event_type text not null,
    language text,
    question_category text,
    matched_project_slug text,
    answered boolean,
    source_count integer,
    response_time_ms integer,
    model_name text,
    error_code text,
    created_at timestamptz not null default now()
);
